### ISSUE TITLE
REST API active check

### ISSUE THREAD

**Issue by mjangda** [scotchfield/rocket-comments#1]
`is_plugin_active( 'rest-api/plugin.php' )` seems a bit fragile (e.g. I might rename the file or folder for some reason). Can we make this more robust?

**Comment by scotchfield** [comment]
Good call, I submitted https://github.com/scotchfield/rocket-comments/commit/9e5ad71787ed7a9212590603d57a0d8dafa3b245 to use defined instead of hard-coding the directory.
