### ISSUE TITLE
Force refresh for no-js

### ISSUE THREAD

**Issue by mjangda** [scotchfield/rocket-comments#2]
It's an interesting workaround but seems a bit heavy-handed. Couldn't a more appropriate choice be to show them a link in place of the comments that links to the nojs version of the page?

**Comment by scotchfield** [comment]
That makes sense, thanks! https://github.com/scotchfield/rocket-comments/commit/f3996467475f38a5d2a05bfe51cfa74579482aa7 replaces the hook and puts the link in the new comment template.
